name: Run QA Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Изтегляне на кода (Checkout)
      uses: actions/checkout@v4

    - name: 2. Налагане на Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Инсталиране на зависимостите
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. Инсталиране на Playwright браузърите
      run: playwright install chromium

    - name: 5. Пускане на тестовете (Pytest)
      run: pytest -v
